### ISSUE TITLE
Cannot install terra_server profile because of missing files.

### ISSUE THREAD

**Issue by theodorosploumis** [terra-ops/terra-server#1]
When I run `terra environment:enable terra_server local` I get a url but I cannot continue with the installation because the **settings.php, sites/default/files, sites/default/services.yml** are missing.

Probably **terra** cannot create these files/folders when running the https://github.com/terra-ops/terra-server/blob/master/.terra.yml. Even if I create the folders/files manually on host Drupal still has no access.

If I get into the container on the machine `terraserverlocal_app_1` I cannot see the folder `/var/terra/`!

I am using Ubuntu 15.04.

**Comment by jonpugh** [comment]
That's strange...  did you run either command environment:add or environment:enable with sudo?

Can you create the settings.php, files and services.yml folder manually?

**Comment by theodorosploumis** [comment]
No, I did not use `sudo`. Should I? Also, I run docker as current user not with sudo (if that is useful).

I can create the files on host (SOME_PATH/terra_server/local/sites/default) but the app has no access. On host  machine these files are owned by current Ubuntu user, not root. But as I said before **the `/var/terra/` folder does not exist on the docker container**!

Can you please send the **permissions/ownership** of the drupal sites/default folder on the host machine as also as on the guest container?

**Comment by jonpugh** [comment]
No, shouldn't use sudo.  You should run `terra` as the same user you run `docker` with....

Are you sure you have the very latest terra? The code to allow mounting of the `/var/terra` folder was only introduced this morning.  Please make sure you run `git pull` in your terra-app directory often.

Permissions set on the host are reflected in the container:

On the left is inside the container. On the right is the host.
![screenshot from 2015-07-11 19 22 52](https://cloud.githubusercontent.com/assets/106420/8635731/481dbc4a-2802-11e5-9ad9-ac176f3dbd23.png)

**Comment by theodorosploumis** [comment]
Oh, I was missing a lot of new terra\* files! Docker containers, local folders, drush aliases etc.
Now it works OK. I had to **uninstall terra, remove ~/.terra folder and add terra to my $PATH** in order to work.
